% This only works if 'FatigueOutcomePlot' has been saved in the subject
% data folder! (i.e. fatiguephaseAnalysis was run on the subject.

clear; clc

rootpath = 'C:\Users\Steven\Documents\FatigueStudy\Data\Pilot Data';

SubjectID = {...
    'KM_72015'...
    'SM_71515'...
    'RL_71415'...
    'ND_72115'...
    'FO_72115'...
    'SG_72215'...
    'AG_72215'...
%     'JH_71515'...
%     'patricktest_71715'...
    };

for i = 1:size(SubjectID,2)
    SubjectDir = char(fullfile(rootpath,SubjectID(i)));
    load(fullfile(SubjectDir,'FatigueOutcomePlot'));
    figure(i);
    plot(outcomePlot,'-o');
end

    